CREATE TABLE S_CHECKITEM_INFO
(
  ITEM_ID         VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_CHECKITEM_INFO
    PRIMARY KEY,
  INFO_TYPE       NUMBER,
  COMPANY_CODE    VARCHAR2(100),
  COMPANY_NAME    VARCHAR2(100),
  CEHCK_CONTENT   VARCHAR2(500),
  ITEM_INFO       CLOB,
  IS_DANGER_CHECK NUMBER DEFAULT 1,
  DANGER_VALUE    VARCHAR2(100),
  DANGER_LEVER    NUMBER DEFAULT 0,
  TYPE_NAME1      VARCHAR2(50),
  TYPE_NAME2      VARCHAR2(50),
  TYPE_NAME3      VARCHAR2(50),
  SORTNO          NUMBER
)
/

COMMENT ON TABLE S_CHECKITEM_INFO IS '检查库表'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.ITEM_ID IS 'ID'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.INFO_TYPE IS '信息类型(0，系统，1单位自定义)'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.COMPANY_CODE IS '单位代码'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.COMPANY_NAME IS '单位名称'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.CEHCK_CONTENT IS '检查内容'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.ITEM_INFO IS '检查信息,json 数组格式'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.IS_DANGER_CHECK IS '判断是否有隐患'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.DANGER_VALUE IS '隐患值'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.DANGER_LEVER IS '隐患等级(0,1,2,3,4隐患等级)'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.TYPE_NAME1 IS '分类名称1(索引)'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.TYPE_NAME2 IS '分类名称2(索引)'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.TYPE_NAME3 IS '分类名称3(索引)'
/

COMMENT ON COLUMN S_CHECKITEM_INFO.SORTNO IS '排序号()由小到大排序'
/

CREATE TABLE S_CHECKITEM_TYPE
(
  TYPE_ID   VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_CHECKITEM_TYPE
    PRIMARY KEY,
  TYPE_NAME VARCHAR2(50),
  PARENT_ID VARCHAR2(100),
  SORTNO    NUMBER,
  GRADE     NUMBER
)
/

COMMENT ON TABLE S_CHECKITEM_TYPE IS '检查项分类表'
/

COMMENT ON COLUMN S_CHECKITEM_TYPE.TYPE_ID IS 'ID'
/

COMMENT ON COLUMN S_CHECKITEM_TYPE.TYPE_NAME IS '分类名称(索引)'
/

COMMENT ON COLUMN S_CHECKITEM_TYPE.PARENT_ID IS '父类ID号(0为第一级)'
/

COMMENT ON COLUMN S_CHECKITEM_TYPE.SORTNO IS '排序号(由小到大排序)'
/

COMMENT ON COLUMN S_CHECKITEM_TYPE.GRADE IS '分类等级(用来判断该类型属于哪一级，如果是第三级就不能添加下级，方便分级
)'
/

CREATE TABLE S_CHECK_CONTENT
(
  CONETN_ID          VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_CHECK_CONTENT
    PRIMARY KEY,
  ITEM_ID            VARCHAR2(100),
  FORM_ID            VARCHAR2(100),
  CONTENT_TITLE      VARCHAR2(100),
  CONTNET_NO         NUMBER,
  SHOW_TYPE          VARCHAR2(20),
  CONTENT_VALUE      NUMBER(5, 1),
  CONTENT_ANSWER     CLOB,
  IS_DANGER_CHECK    NUMBER DEFAULT 1,
  DANGER_VALUE       VARCHAR2(150),
  DANGER_LEVER       NUMBER DEFAULT 0,
  CONTENT_ITEMS      VARCHAR2(500),
  ISDANAGERSHOW      NUMBER DEFAULT 0,
  ISEXITSOTHER       NUMBER DEFAULT 1,
  ISEXITESVIDIO      NUMBER DEFAULT 0,
  ISEXITESPHOTO      NUMBER,
  ISEXITESAUDIO      NUMBER,
  ISEXITESFILEUPLOAD NUMBER,
  UPLOAD_FILE_TYPE   VARCHAR2(100),
  CREATE_TIME        VARCHAR2(20),
  CREATE_USER        VARCHAR2(50),
  UPDATE_TIME        VARCHAR2(20),
  UPDATE_USER        VARCHAR2(50),
  TYPE_NAME1         VARCHAR2(50),
  TYPE_NAME2         VARCHAR2(50),
  TYPE_NAME3         VARCHAR2(50)
)
/

COMMENT ON TABLE S_CHECK_CONTENT IS '检查内容表'
/

COMMENT ON COLUMN S_CHECK_CONTENT.CONETN_ID IS 'ID'
/

COMMENT ON COLUMN S_CHECK_CONTENT.ITEM_ID IS '检查内容库ID(自定义时不存在，索引，可通过检查内容库选择)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.FORM_ID IS '表单ID号(索引)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.CONTENT_TITLE IS '标题内容'
/

COMMENT ON COLUMN S_CHECK_CONTENT.CONTNET_NO IS '编号(由小到大排序)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.SHOW_TYPE IS '显示方式,(text(文本),radio(单选,checkbox(多选))'
/

COMMENT ON COLUMN S_CHECK_CONTENT.CONTENT_VALUE IS '单项分值(一位小数)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.CONTENT_ANSWER IS '答案(对应CONTENT_ITEMS中的itemNo。必须全部匹配才得分。多个答案为逗号分隔的字符串.1234567)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.IS_DANGER_CHECK IS '是否有隐患判断'
/

COMMENT ON COLUMN S_CHECK_CONTENT.DANGER_VALUE IS '隐患值'
/

COMMENT ON COLUMN S_CHECK_CONTENT.DANGER_LEVER IS '隐患等级,(0,1,2,3,4隐患等级)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.CONTENT_ITEMS IS '选项(json数组
[{itemNo:1;itemTitle:xx;itemValue:0}]
itemno全部采用1234567来表示序号n)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.ISDANAGERSHOW IS '是否有隐患时才可上传(0否，1是, 选择1时只有选择了有隐患时才显示图片视频等上传内容)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.ISEXITSOTHER IS '是否有其它,0无，1有，有其它时，可手工输入内容。'
/

COMMENT ON COLUMN S_CHECK_CONTENT.ISEXITESVIDIO IS '是否有视频上传,0无，1有。'
/

COMMENT ON COLUMN S_CHECK_CONTENT.ISEXITESPHOTO IS '是否有图片上传,0无，1有。'
/

COMMENT ON COLUMN S_CHECK_CONTENT.ISEXITESAUDIO IS '是否有声音上传,0无，1有。'
/

COMMENT ON COLUMN S_CHECK_CONTENT.ISEXITESFILEUPLOAD IS '是否有文件上传,0无，1有。'
/

COMMENT ON COLUMN S_CHECK_CONTENT.UPLOAD_FILE_TYPE IS '允许上传文件类型(.DOC.DOCX等)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.CREATE_TIME IS '创建时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN S_CHECK_CONTENT.UPDATE_TIME IS '更新时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.UPDATE_USER IS '更新用户名'
/

COMMENT ON COLUMN S_CHECK_CONTENT.TYPE_NAME1 IS '分类名称1(索引)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.TYPE_NAME2 IS '分类名称2(索引)'
/

COMMENT ON COLUMN S_CHECK_CONTENT.TYPE_NAME3 IS '分类名称3(索引)'
/

CREATE TABLE S_COMPANY_INFO
(
  COMPANY_ID              VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_COMPANY_INFO
    PRIMARY KEY,
  COMPANY_CODE            VARCHAR2(100),
  COMPANY_NAME            VARCHAR2(100),
  COMPANY_TYPE            VARCHAR2(100),
  PY_COMPANY              VARCHAR2(100),
  PNAME                   VARCHAR2(30),
  CNAME                   VARCHAR2(30),
  DNAME                   VARCHAR2(30),
  STREETNAME              VARCHAR2(50),
  PARENT_CODE             VARCHAR2(100),
  PARENT_NAME             VARCHAR2(50),
  ORG_CODE                VARCHAR2(50),
  COMPANY_TEL             VARCHAR2(20),
  COMPANY_ADDRESS         VARCHAR2(100),
  GPS_LNG                 VARCHAR2(20),
  GPS_LAT                 VARCHAR2(20),
  COMPANY_ZIP             VARCHAR2(20),
  COMPANY_DEPARTMENTS     CLOB,
  FIRST_LEADER            VARCHAR2(50),
  FIRST_LEADER_MOBILE     VARCHAR2(20),
  LEADER_PERSON           VARCHAR2(50),
  CONTACT_PERSON          VARCHAR2(50),
  CONTACT_PERSON_MOBILE   VARCHAR2(50),
  SAFTY_PERSON            VARCHAR2(50),
  REGISTER_TYPE           NUMBER,
  REGISTER_TIME           VARCHAR2(20),
  STATUS                  NUMBER,
  SAFE_MANAGER_DEPARTMENT VARCHAR2(50),
  SAFE_PERSONNUM          NUMBER,
  CREATE_TIME             VARCHAR2(20),
  CREATE_USER             VARCHAR2(50),
  UPDATE_TIME             VARCHAR2(20),
  UPDATE_USER             VARCHAR2(50)
)
/

COMMENT ON TABLE S_COMPANY_INFO IS '单位信息表'
/

COMMENT ON COLUMN S_COMPANY_INFO.COMPANY_ID IS '单位ID(主键longTime+”-"+javauuid（唯一）)'
/

COMMENT ON COLUMN S_COMPANY_INFO.COMPANY_CODE IS '公司编码系统,(没有，手动分配3101010001前两位为省代码3,4位为市代码5,6位为区代码7-11为街道代码（或企业代码）12-16（企业代码）前6位对应S_DISTRICT中的DCODE唯一索引。原则上按组织机构编码，但注意有些单位尽管位于某一个区，但上级机构代码可能不属于区。以上级单位编码为准
)'
/

COMMENT ON COLUMN S_COMPANY_INFO.COMPANY_NAME IS '单位名称'
/

COMMENT ON COLUMN S_COMPANY_INFO.COMPANY_TYPE IS '单位类型'
/

COMMENT ON COLUMN S_COMPANY_INFO.PY_COMPANY IS '单位拼音(对应S_COMPANY_TYPE中的COMPANY_TYPE)'
/

COMMENT ON COLUMN S_COMPANY_INFO.PNAME IS '省(中文，对应S_DISTRICT的DNAME，冗余)'
/

COMMENT ON COLUMN S_COMPANY_INFO.CNAME IS '市(S_DISTRICT的DNAME，冗余)'
/

COMMENT ON COLUMN S_COMPANY_INFO.DNAME IS '区县(S_DISTRICT的DNAME，冗余n上海以该字段建索引n)'
/

COMMENT ON COLUMN S_COMPANY_INFO.STREETNAME IS '街道（乡镇）'
/

COMMENT ON COLUMN S_COMPANY_INFO.PARENT_CODE IS '上级代码(索引，对应COMPANY_CODE
上海第一级父代码为310101.
)'
/

COMMENT ON COLUMN S_COMPANY_INFO.PARENT_NAME IS '上级机构名称(父机构，冗余，便于查询)'
/

COMMENT ON COLUMN S_COMPANY_INFO.ORG_CODE IS '组织机构代码(业机构代码或组织机构代码证号，唯一，只做登记用)'
/

COMMENT ON COLUMN S_COMPANY_INFO.COMPANY_TEL IS '电话'
/

COMMENT ON COLUMN S_COMPANY_INFO.COMPANY_ADDRESS IS '地址'
/

COMMENT ON COLUMN S_COMPANY_INFO.GPS_LNG IS '地址经度(对应百度api的值n预留，暂不实现n)'
/

COMMENT ON COLUMN S_COMPANY_INFO.GPS_LAT IS '地址纬度(对应百度api的值n预留，暂不实现n)'
/

COMMENT ON COLUMN S_COMPANY_INFO.COMPANY_ZIP IS '邮编'
/

COMMENT ON COLUMN S_COMPANY_INFO.COMPANY_DEPARTMENTS IS '单位部门(用逗号分隔的多个部门。便于录入用户时选择。)'
/

COMMENT ON COLUMN S_COMPANY_INFO.FIRST_LEADER IS '第一责任人(第一责任人、校长、法人)'
/

COMMENT ON COLUMN S_COMPANY_INFO.FIRST_LEADER_MOBILE IS '第一责任人电话'
/

COMMENT ON COLUMN S_COMPANY_INFO.LEADER_PERSON IS '责任人'
/

COMMENT ON COLUMN S_COMPANY_INFO.CONTACT_PERSON IS '日常工作联系人、安全负责人，'
/

COMMENT ON COLUMN S_COMPANY_INFO.CONTACT_PERSON_MOBILE IS '日常工作负责人电话'
/

COMMENT ON COLUMN S_COMPANY_INFO.SAFTY_PERSON IS '安全联络员'
/

COMMENT ON COLUMN S_COMPANY_INFO.REGISTER_TYPE IS '注册类型'
/

COMMENT ON COLUMN S_COMPANY_INFO.REGISTER_TIME IS '注册时间(yyyy-mm-dd hh:MM:ss)'
/

COMMENT ON COLUMN S_COMPANY_INFO.STATUS IS '状态(0正常1 已注销2已关停3信息有误)'
/

COMMENT ON COLUMN S_COMPANY_INFO.SAFE_MANAGER_DEPARTMENT IS '安全管理部门'
/

COMMENT ON COLUMN S_COMPANY_INFO.SAFE_PERSONNUM IS '专职安全员数'
/

COMMENT ON COLUMN S_COMPANY_INFO.CREATE_TIME IS '创建时间'
/

COMMENT ON COLUMN S_COMPANY_INFO.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN S_COMPANY_INFO.UPDATE_TIME IS '更新时间'
/

COMMENT ON COLUMN S_COMPANY_INFO.UPDATE_USER IS '更新用户名'
/

CREATE TABLE S_COMPANY_MODEL
(
  COMPANY_ID VARCHAR2(100),
  MODEL_CODE VARCHAR2(50)
)
/

COMMENT ON TABLE S_COMPANY_MODEL IS '单位模块表,暂不使用，单位开通的模块列表'
/

COMMENT ON COLUMN S_COMPANY_MODEL.COMPANY_ID IS '单位ID'
/

COMMENT ON COLUMN S_COMPANY_MODEL.MODEL_CODE IS '功能代码'
/

CREATE TABLE S_DICT_TYPE
(
  ID         VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_DICT_TYPE
    PRIMARY KEY,
  SORTNO     NUMBER,
  DIC_NAME   VARCHAR2(50),
  DIC_TYPE   VARCHAR2(50),
  DIC_CODE   VARCHAR2(50),
  DIC_DESC   VARCHAR2(100),
  DIC_STATUS NUMBER DEFAULT 0
)
/

COMMENT ON TABLE S_DICT_TYPE IS '系统字典表'
/

COMMENT ON COLUMN S_DICT_TYPE.ID IS '主键'
/

COMMENT ON COLUMN S_DICT_TYPE.SORTNO IS '排序号(由小到大排序)'
/

COMMENT ON COLUMN S_DICT_TYPE.DIC_NAME IS '字典名称'
/

COMMENT ON COLUMN S_DICT_TYPE.DIC_TYPE IS '配置代码'
/

COMMENT ON COLUMN S_DICT_TYPE.DIC_CODE IS '字典CODE'
/

COMMENT ON COLUMN S_DICT_TYPE.DIC_DESC IS '备注'
/

COMMENT ON COLUMN S_DICT_TYPE.DIC_STATUS IS '状态 0 启动 1 禁用'
/

CREATE TABLE S_DISTRICT
(
  DCODE       VARCHAR2(50),
  DNAME       VARCHAR2(50),
  PARENT_CODE VARCHAR2(50)
)
/

COMMENT ON TABLE S_DISTRICT IS '地区表'
/

COMMENT ON COLUMN S_DISTRICT.DCODE IS '地区代码 (主键，上海31)'
/

COMMENT ON COLUMN S_DISTRICT.DNAME IS '地区名称(英文，唯一)'
/

COMMENT ON COLUMN S_DISTRICT.PARENT_CODE IS '父代码'
/

CREATE TABLE S_ENTITY_INFO
(
  ENTITY_ID    VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_ENTITY_INFO
    PRIMARY KEY,
  TABLE_NAME   VARCHAR2(100),
  FIELD_NAME   VARCHAR2(100),
  FIELD_CODE   VARCHAR2(100),
  FIELD_TYPE   VARCHAR2(100),
  FIELD_LENGTH NUMBER,
  DATA_TYPE    VARCHAR2(100),
  DATA_CHECK   NUMBER,
  COMPANY_CODE VARCHAR2(100),
  CREATE_TIME  VARCHAR2(20),
  CREATE_USER  VARCHAR2(50),
  UPDATE_TIME  VARCHAR2(20),
  UPDATE_USER  VARCHAR2(50)
)
/

COMMENT ON TABLE S_ENTITY_INFO IS '自定义实体表信息  ( 同一数据库表是先删除再增加方式产生数据。 )'
/

COMMENT ON COLUMN S_ENTITY_INFO.ENTITY_ID IS 'ID'
/

COMMENT ON COLUMN S_ENTITY_INFO.TABLE_NAME IS '表名'
/

COMMENT ON COLUMN S_ENTITY_INFO.FIELD_NAME IS '字段名称'
/

COMMENT ON COLUMN S_ENTITY_INFO.FIELD_CODE IS '字段代码(全大写英文字母)'
/

COMMENT ON COLUMN S_ENTITY_INFO.FIELD_TYPE IS '字段类型(TEXT,INT,DECEIMAL,对应数据库类型)'
/

COMMENT ON COLUMN S_ENTITY_INFO.FIELD_LENGTH IS '字段长度（默认50，超过500用TEXT创建）'
/

COMMENT ON COLUMN S_ENTITY_INFO.DATA_TYPE IS '数据类型(INT数字,TIME时间,DATE日期,TEXT字符，EMAIL，MOBILE手机号,DECIMAL)'
/

COMMENT ON COLUMN S_ENTITY_INFO.DATA_CHECK IS '数据检查(0不判断1必须判断2非空时判断)'
/

COMMENT ON COLUMN S_ENTITY_INFO.COMPANY_CODE IS '所属单位(表单归属单位)'
/

COMMENT ON COLUMN S_ENTITY_INFO.CREATE_TIME IS '创建时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN S_ENTITY_INFO.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN S_ENTITY_INFO.UPDATE_TIME IS '更新时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN S_ENTITY_INFO.UPDATE_USER IS '更新用户名'
/

CREATE TABLE S_FORM_INFO
(
  FORM_ID          VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_FORM_INFO
    PRIMARY KEY,
  FORM_TYPE        NUMBER,
  INPUT_TYPE       NUMBER,
  FORM_NAME        VARCHAR2(100),
  TEMPLATE_CONTENT CLOB,
  TABLE_NAME       VARCHAR2(100),
  OPEN_STATUS      NUMBER,
  COMPANY_CODE     VARCHAR2(100),
  CREATE_TIME      VARCHAR2(20),
  CREATE_USER      VARCHAR2(50),
  UPDATE_TIME      VARCHAR2(20),
  UPDATE_USER      VARCHAR2(50),
  START_TIME       VARCHAR2(20),
  END_TIME         VARCHAR2(20)
)
/

COMMENT ON TABLE S_FORM_INFO IS '自定义表单表'
/

COMMENT ON COLUMN S_FORM_INFO.FORM_TYPE IS '表单类型(0，选项表单（通过检查项设置），1模板文件表单（通过模板文件设置）,2其它填报表单（暂无需求，不依赖任务可以直接发布，默认对所有人要求）)'
/

COMMENT ON COLUMN S_FORM_INFO.INPUT_TYPE IS '填报类型(任务表单输入类型任务设置，非任务表单通过这个来限制输入类型0不限制可随时填报1每周1次，2每月1次3只一次)'
/

COMMENT ON COLUMN S_FORM_INFO.FORM_NAME IS '表单名称'
/

COMMENT ON COLUMN S_FORM_INFO.TEMPLATE_CONTENT IS '模板文件(模板html代码)'
/

COMMENT ON COLUMN S_FORM_INFO.TABLE_NAME IS '实体表名称(唯一，只能创建一个实体表
创建的实体表默认包含一些字段。n)'
/

COMMENT ON COLUMN S_FORM_INFO.OPEN_STATUS IS '开发状态(0未开放1已开放)'
/

COMMENT ON COLUMN S_FORM_INFO.COMPANY_CODE IS '所属单位(表单归属单位)'
/

COMMENT ON COLUMN S_FORM_INFO.CREATE_TIME IS '创建时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN S_FORM_INFO.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN S_FORM_INFO.UPDATE_TIME IS '更新时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN S_FORM_INFO.UPDATE_USER IS '更新用户名'
/

COMMENT ON COLUMN S_FORM_INFO.START_TIME IS '其他填报开始时间'
/

COMMENT ON COLUMN S_FORM_INFO.END_TIME IS '其他填报结束时间'
/

CREATE TABLE S_FUNCTIONINFO
(
  FUNCTION_ID   VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_FUNCTIONINFO
    PRIMARY KEY,
  FUNCTION_CODE VARCHAR2(200),
  FUNCTION_NAME VARCHAR2(100),
  PARENT_ID     VARCHAR2(100),
  SORT_NO       NUMBER,
  FUNCTION_TYPE NUMBER,
  MODEL_CODE    VARCHAR2(100) DEFAULT '0'
)
/

COMMENT ON TABLE S_FUNCTIONINFO IS '系统功能表,不做页面维护，通过初始化操作，对应代码编码文件'
/

COMMENT ON COLUMN S_FUNCTIONINFO.FUNCTION_ID IS '单位ID'
/

COMMENT ON COLUMN S_FUNCTIONINFO.FUNCTION_CODE IS '功能代码,控制代码，对应代码中的控制代码(可分配url类型，但必须严格按照代码传递参数来设置)'
/

COMMENT ON COLUMN S_FUNCTIONINFO.FUNCTION_NAME IS '功能名称,'
/

COMMENT ON COLUMN S_FUNCTIONINFO.PARENT_ID IS '父代码,0父级，只显示。'
/

COMMENT ON COLUMN S_FUNCTIONINFO.SORT_NO IS '排序号,由小到大排序，偏于权限分配中显示'
/

COMMENT ON COLUMN S_FUNCTIONINFO.FUNCTION_TYPE IS '函数类型,0,控制代码，1 url类型，2操作按钮、3数据筛选类型。暂不使用，如果同时企业url和控制代码方式需要设置。'
/

COMMENT ON COLUMN S_FUNCTIONINFO.MODEL_CODE IS '功能模块代码,对应功能模块代码'
/

CREATE TABLE S_ROLEINFO
(
  ROLE_ID   VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_ROLEINFO
    PRIMARY KEY,
  ROLE_CODE VARCHAR2(50),
  ROLE_NAME VARCHAR2(100),
  ROLE_DESC VARCHAR2(200)
)
/

COMMENT ON TABLE S_ROLEINFO IS '系统角色表  配置界面，ROLE_CODE暂时不做录入'
/

COMMENT ON COLUMN S_ROLEINFO.ROLE_ID IS '角色ID(主键、LONGTIME+”-"+JAVAUUID（唯一）)'
/

COMMENT ON COLUMN S_ROLEINFO.ROLE_CODE IS '角色代码'
/

COMMENT ON COLUMN S_ROLEINFO.ROLE_NAME IS '角色名称'
/

COMMENT ON COLUMN S_ROLEINFO.ROLE_DESC IS '备注(角色描述)'
/

CREATE TABLE S_ROLE_FUNTION
(
  ROLE_ID     VARCHAR2(100) NOT NULL,
  FUNCTION_ID VARCHAR2(50)  NOT NULL,
  CONSTRAINT PK_S_ROLE_FUNTION
  PRIMARY KEY (ROLE_ID, FUNCTION_ID)
)
/

COMMENT ON TABLE S_ROLE_FUNTION IS '维护修改时，先删除角色下所有功能信息，重新新增角色下功能信息'
/

COMMENT ON COLUMN S_ROLE_FUNTION.ROLE_ID IS '角色ID'
/

COMMENT ON COLUMN S_ROLE_FUNTION.FUNCTION_ID IS '功能ID'
/

CREATE TABLE S_SYSTEM_MODEL
(
  MODEL_CODE VARCHAR2(50),
  MODEL_NAME VARCHAR2(50)
)
/

COMMENT ON TABLE S_SYSTEM_MODEL IS '系统模块表'
/

COMMENT ON COLUMN S_SYSTEM_MODEL.MODEL_CODE IS '模块代码'
/

COMMENT ON COLUMN S_SYSTEM_MODEL.MODEL_NAME IS '模块名称'
/

CREATE TABLE S_USER_EXTNED_RIGHT
(
  USER_ID       VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_USER_EXTNED_RIGHT
    PRIMARY KEY,
  REGISTER_TYPE NUMBER DEFAULT 0,
  COMPANY_INFO  NUMBER DEFAULT 0,
  CHECK_POINT   NUMBER DEFAULT 0,
  CREATE_TIME   VARCHAR2(20),
  CREATE_USER   VARCHAR2(50),
  UPDATE_TIME   VARCHAR2(20),
  UPDATE_USER   VARCHAR2(50)
)
/

COMMENT ON TABLE S_USER_EXTNED_RIGHT IS '用户权限扩展表'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT.USER_ID IS '角色ID'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT.REGISTER_TYPE IS '单位注册类型扩展(0不扩展1扩展,为1时，必须在nS_USER_EXTNED_REGISTER_TYPE存在记录
)'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT.COMPANY_INFO IS '管理单位扩展(0默认不扩展，1含下级所有单位2仅限选定单位，3除下级单位外、包含选定单位，4不包含选定单位。)'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT.CHECK_POINT IS '检查点（设备）(0默认不扩展，1限定选定的检查点)'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT.CREATE_TIME IS '创建时间'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT.UPDATE_TIME IS '更新时间'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT.UPDATE_USER IS '更新用户名'
/

CREATE TABLE S_USER_EXTNED_RIGHT_DETAIL
(
  EXTEND_ID    VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_USER_EXTNED_RIGHT_DETAIL
    PRIMARY KEY,
  EXTEND_TYPE  NUMBER DEFAULT 0,
  USER_ID      VARCHAR2(100),
  EXTEND_VALUE VARCHAR2(200)
)
/

COMMENT ON TABLE S_USER_EXTNED_RIGHT_DETAIL IS '用户权限扩展明细表,该表存在记录，n则S_USER_EXTNED_RIGHT中相应类型字段为1，nS_USER_INFO中IS_EXTEND_RIGHT为1。'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT_DETAIL.EXTEND_ID IS 'ID'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT_DETAIL.EXTEND_TYPE IS '扩展类型(0，管理单位扩展，1注册类型（单位类型提示）扩展，2检查点（后续需要）)'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT_DETAIL.USER_ID IS '用户ID(索引)'
/

COMMENT ON COLUMN S_USER_EXTNED_RIGHT_DETAIL.EXTEND_VALUE IS '注册类型(对于管理单位则为单位ID号，
对于注册类型则为注册类型值，对于其它则为相应的主键值n)'
/

CREATE TABLE S_USER_INFO
(
  USER_ID         VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_USER_INFO
    PRIMARY KEY,
  USER_NAME       VARCHAR2(50),
  USER_CODE       VARCHAR2(50),
  PASSWORD        VARCHAR2(100),
  COMPANY_ID      VARCHAR2(100),
  COMPANY_NAME    VARCHAR2(100),
  DEPARTMENT_NAME VARCHAR2(50),
  POSITION_NAME   VARCHAR2(50),
  MOBILE          VARCHAR2(20),
  EMAIL           VARCHAR2(100),
  LAST_LOGIN_TIME VARCHAR2(20),
  LAST_LOGIN_IP   VARCHAR2(20),
  PY_USER         VARCHAR2(20),
  OPEN_TYPE       NUMBER DEFAULT 1,
  STATUS          NUMBER,
  IS_EXTEND_RIGHT NUMBER DEFAULT 0,
  CREATE_TIME     VARCHAR2(20),
  CREATE_USER     VARCHAR2(50),
  UPDATE_TIME     VARCHAR2(20),
  UPDATE_USER     VARCHAR2(50)
)
/

COMMENT ON TABLE S_USER_INFO IS '用户信息表'
/

COMMENT ON COLUMN S_USER_INFO.USER_ID IS '主键LONGTIME+”-"+JAVA UUID（唯一）ID'
/

COMMENT ON COLUMN S_USER_INFO.USER_NAME IS '用户名'
/

COMMENT ON COLUMN S_USER_INFO.USER_CODE IS '账号(唯一索引)'
/

COMMENT ON COLUMN S_USER_INFO.PASSWORD IS '密码(MD5加密，使用统一加密函数加密)'
/

COMMENT ON COLUMN S_USER_INFO.COMPANY_ID IS '所属单位ID(索引)'
/

COMMENT ON COLUMN S_USER_INFO.COMPANY_NAME IS '单位名称(冗余，便于单表查询)'
/

COMMENT ON COLUMN S_USER_INFO.DEPARTMENT_NAME IS '所属部门（可手工录入，可通过单位信息中部门选择）'
/

COMMENT ON COLUMN S_USER_INFO.POSITION_NAME IS '职务'
/

COMMENT ON COLUMN S_USER_INFO.MOBILE IS '电话'
/

COMMENT ON COLUMN S_USER_INFO.EMAIL IS 'EMAIL'
/

COMMENT ON COLUMN S_USER_INFO.LAST_LOGIN_TIME IS '上次登录时间'
/

COMMENT ON COLUMN S_USER_INFO.LAST_LOGIN_IP IS '上次登录IP'
/

COMMENT ON COLUMN S_USER_INFO.OPEN_TYPE IS '开放类型(0不开放，1本单位开放，2对上级开放，3同级开放，4下级开放，5所有开放)'
/

COMMENT ON COLUMN S_USER_INFO.STATUS IS '状态(0不可用1 可用)'
/

COMMENT ON COLUMN S_USER_INFO.IS_EXTEND_RIGHT IS '是否扩展权限(0不扩展，1扩展，扩展后登陆后才会判断规则，进入权限扩展界面。)'
/

COMMENT ON COLUMN S_USER_INFO.CREATE_TIME IS '创建时间'
/

COMMENT ON COLUMN S_USER_INFO.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN S_USER_INFO.UPDATE_TIME IS '更新时间'
/

COMMENT ON COLUMN S_USER_INFO.UPDATE_USER IS '更新用户名'
/

CREATE TABLE S_USER_ROLE
(
  USER_ID VARCHAR2(100) NOT NULL,
  ROLE_ID VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_S_USER_ROLE
  PRIMARY KEY (USER_ID, ROLE_ID)
)
/

COMMENT ON TABLE S_USER_ROLE IS '用户角色表n维护修改时，先删除用户下所有角色后，n再重新新增角色信息。一个用户可多个角色。'
/

COMMENT ON COLUMN S_USER_ROLE.USER_ID IS '用户ID'
/

COMMENT ON COLUMN S_USER_ROLE.ROLE_ID IS '角色ID'
/

CREATE TABLE S_WEB_CONFIG
(
  ID            VARCHAR2(100) NOT NULL
    CONSTRAINT PK_S_WEB_CONFIG
    PRIMARY KEY,
  CONFIG_CODE   VARCHAR2(100),
  CONFIG_VALUE  CLOB,
  CONFIG_STATUS NUMBER(5),
  CONFIG_DESC   VARCHAR2(100),
  CREATE_TIME   VARCHAR2(20),
  CREATE_USER   VARCHAR2(50),
  UPDATE_TIME   VARCHAR2(20),
  UPDATE_USER   VARCHAR2(50)
)
/

COMMENT ON TABLE S_WEB_CONFIG IS '配置总表'
/

COMMENT ON COLUMN S_WEB_CONFIG.ID IS '主键，longTime+”-"+uuid'
/

COMMENT ON COLUMN S_WEB_CONFIG.CONFIG_CODE IS '配置代码,英文，唯一'
/

COMMENT ON COLUMN S_WEB_CONFIG.CONFIG_VALUE IS '值,可多种格式录入，如json等'
/

COMMENT ON COLUMN S_WEB_CONFIG.CONFIG_STATUS IS '状态   0不可用、1可用'
/

COMMENT ON COLUMN S_WEB_CONFIG.CONFIG_DESC IS '描述: 备注'
/

COMMENT ON COLUMN S_WEB_CONFIG.CREATE_TIME IS '创建时间 格式：  yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN S_WEB_CONFIG.CREATE_USER IS '创建用户：用户名'
/

COMMENT ON COLUMN S_WEB_CONFIG.UPDATE_TIME IS '更新时间  格式：  yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN S_WEB_CONFIG.UPDATE_USER IS '更新用户：用户名'
/

CREATE TABLE T_ATTACH_INFO
(
  ID            VARCHAR2(64) NOT NULL
    CONSTRAINT PK_T_ATTACH_INFO
    PRIMARY KEY,
  REFER_ID      VARCHAR2(64),
  REFER_TABLE   VARCHAR2(50),
  TASK_NAME     VARCHAR2(100),
  TYPE_NAME1    VARCHAR2(50),
  TYPE_NAME2    VARCHAR2(50),
  TYPE_NAME3    VARCHAR2(50),
  TASK_FROM     VARCHAR2(50),
  COMPANY_NAME  VARCHAR2(100),
  COMPANY_CODE  VARCHAR2(100),
  ATTACH_TYPE   NUMBER,
  ATTACH_URL    VARCHAR2(500),
  ATTACH_NAME   VARCHAR2(255),
  REMARKS       VARCHAR2(200),
  FILE_SIZE     VARCHAR2(100),
  ATTACH_STATUS NUMBER,
  GPS_LNG       VARCHAR2(20),
  GPS_LAT       VARCHAR2(20),
  ATTACH_SUFFIX VARCHAR2(20),
  ATTACH_YEAR   VARCHAR2(10),
  ATTACH_MONTH  VARCHAR2(10),
  ATTACH_DATE   VARCHAR2(10),
  ATTACH_WEEK   NUMBER,
  CREATE_USER   VARCHAR2(50),
  CREATE_TIME   VARCHAR2(20),
  UPDATE_TIME   VARCHAR2(20),
  UPDATE_USER   VARCHAR2(50)
)
/

COMMENT ON TABLE T_ATTACH_INFO IS '附件表'
/

COMMENT ON COLUMN T_ATTACH_INFO.ID IS '主键ID'
/

COMMENT ON COLUMN T_ATTACH_INFO.REFER_ID IS '引用者ID'
/

COMMENT ON COLUMN T_ATTACH_INFO.REFER_TABLE IS '引用表名称'
/

COMMENT ON COLUMN T_ATTACH_INFO.TASK_NAME IS '任务名称'
/

COMMENT ON COLUMN T_ATTACH_INFO.TYPE_NAME1 IS '检查项分类名称1'
/

COMMENT ON COLUMN T_ATTACH_INFO.TYPE_NAME2 IS '检查项分类名称2'
/

COMMENT ON COLUMN T_ATTACH_INFO.TYPE_NAME3 IS '检查项分类名称3'
/

COMMENT ON COLUMN T_ATTACH_INFO.TASK_FROM IS '附件来源'
/

COMMENT ON COLUMN T_ATTACH_INFO.COMPANY_NAME IS '归属单位名称'
/

COMMENT ON COLUMN T_ATTACH_INFO.COMPANY_CODE IS '归属单位代码'
/

COMMENT ON COLUMN T_ATTACH_INFO.ATTACH_TYPE IS '附件类型（如：任务，检查项）'
/

COMMENT ON COLUMN T_ATTACH_INFO.ATTACH_URL IS '附件访问地址'
/

COMMENT ON COLUMN T_ATTACH_INFO.ATTACH_NAME IS '附件名称'
/

COMMENT ON COLUMN T_ATTACH_INFO.REMARKS IS '备注'
/

COMMENT ON COLUMN T_ATTACH_INFO.FILE_SIZE IS '文件大小'
/

COMMENT ON COLUMN T_ATTACH_INFO.ATTACH_STATUS IS '删除标志 0:删除 1：有效'
/

COMMENT ON COLUMN T_ATTACH_INFO.GPS_LNG IS '地址经度'
/

COMMENT ON COLUMN T_ATTACH_INFO.GPS_LAT IS '地址纬度'
/

COMMENT ON COLUMN T_ATTACH_INFO.ATTACH_SUFFIX IS '后缀'
/

COMMENT ON COLUMN T_ATTACH_INFO.ATTACH_YEAR IS '年'
/

COMMENT ON COLUMN T_ATTACH_INFO.ATTACH_MONTH IS '两位月01,02'
/

COMMENT ON COLUMN T_ATTACH_INFO.ATTACH_DATE IS '8位日期YYYYMMDD'
/

COMMENT ON COLUMN T_ATTACH_INFO.ATTACH_WEEK IS '周'
/

COMMENT ON COLUMN T_ATTACH_INFO.CREATE_USER IS '创建人'
/

COMMENT ON COLUMN T_ATTACH_INFO.CREATE_TIME IS '创建时间'
/

COMMENT ON COLUMN T_ATTACH_INFO.UPDATE_TIME IS '更新时间'
/

COMMENT ON COLUMN T_ATTACH_INFO.UPDATE_USER IS '更新人'
/

CREATE TABLE T_CHECK_INFO
(
  CHECK_RESULT_ID           VARCHAR2(100) NOT NULL
    CONSTRAINT PK_T_CHECK_INFO
    PRIMARY KEY,
  TASK_ID                   VARCHAR2(100),
  FORM_ID                   VARCHAR2(100),
  TASK_FROM                 VARCHAR2(100),
  FORM_NAME                 VARCHAR2(100),
  TABLE_NAME                VARCHAR2(100),
  TABLE_ID                  VARCHAR2(100),
  PNAME                     VARCHAR2(30),
  CNAME                     VARCHAR2(30),
  DNAME                     VARCHAR2(30),
  STREETNAME                VARCHAR2(30),
  SCORE                     NUMBER(5, 1),
  CHECK_RESULT              NUMBER DEFAULT 0,
  CHECK_STATUS              NUMBER,
  COMPANY_ID                VARCHAR2(100),
  COMPANY_CODE              VARCHAR2(100),
  COMPANY_NAME              VARCHAR2(100),
  CHECK_COMPANY_CODE        VARCHAR2(100),
  CHECK_COMPANY_NAME        VARCHAR2(100),
  PARENT_CODE               VARCHAR2(100),
  CHECK_BELONG_COMPANY_CODE VARCHAR2(100),
  CHECK_USER_ID             VARCHAR2(100),
  CHECK_USER_NAME           VARCHAR2(50),
  CHECK_YEAR                VARCHAR2(10),
  CHECK_MONTH               VARCHAR2(10),
  CHECK_DATE                VARCHAR2(10),
  CHECK_WEEK                NUMBER,
  CREATE_TIME               VARCHAR2(20),
  CREATE_USER               VARCHAR2(50),
  UPDATE_TIME               VARCHAR2(20),
  UPDATE_USER               VARCHAR2(50)
)
/

COMMENT ON TABLE T_CHECK_INFO IS '检查信息表'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_RESULT_ID IS 'ID'
/

COMMENT ON COLUMN T_CHECK_INFO.TASK_ID IS '任务ID'
/

COMMENT ON COLUMN T_CHECK_INFO.FORM_ID IS '表单ID'
/

COMMENT ON COLUMN T_CHECK_INFO.TASK_FROM IS '任务来源'
/

COMMENT ON COLUMN T_CHECK_INFO.FORM_NAME IS '检查点名称(冗余字段)'
/

COMMENT ON COLUMN T_CHECK_INFO.TABLE_NAME IS '主表名（根据TASK_FROM 对应不同的表）'
/

COMMENT ON COLUMN T_CHECK_INFO.TABLE_ID IS '主表ID值（对应的主表名ID值）'
/

COMMENT ON COLUMN T_CHECK_INFO.PNAME IS '省'
/

COMMENT ON COLUMN T_CHECK_INFO.CNAME IS '市'
/

COMMENT ON COLUMN T_CHECK_INFO.DNAME IS '区县'
/

COMMENT ON COLUMN T_CHECK_INFO.STREETNAME IS '街道（乡镇）'
/

COMMENT ON COLUMN T_CHECK_INFO.SCORE IS '得分（获得分数，1位小数）'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_RESULT IS '是否正常（0正常1异常（有隐患））'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_STATUS IS '状态 0未开始，1未完成，2已完成'
/

COMMENT ON COLUMN T_CHECK_INFO.COMPANY_ID IS '所属单位ID号'
/

COMMENT ON COLUMN T_CHECK_INFO.COMPANY_CODE IS '所属单位代码（目标单位、检查点（设备等）单位代码）'
/

COMMENT ON COLUMN T_CHECK_INFO.COMPANY_NAME IS '单位名称（检查点单位名称）'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_COMPANY_CODE IS '检查单位代码'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_COMPANY_NAME IS '检查单位(执行填报的单位名称)'
/

COMMENT ON COLUMN T_CHECK_INFO.PARENT_CODE IS '父代码(检查点单位父代码)'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_BELONG_COMPANY_CODE IS '检查归属单位,(检查表单归属单位，冗余
同表单归属相同。n)'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_USER_ID IS '用户ID,检查人ID'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_USER_NAME IS '检查用户名'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_YEAR IS '4位年'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_MONTH IS '两位月01,02'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_DATE IS '8位日期YYYYMMDD'
/

COMMENT ON COLUMN T_CHECK_INFO.CHECK_WEEK IS '1-7周1，7周日'
/

COMMENT ON COLUMN T_CHECK_INFO.CREATE_TIME IS '创建时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN T_CHECK_INFO.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN T_CHECK_INFO.UPDATE_TIME IS '更新时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN T_CHECK_INFO.UPDATE_USER IS '更新用户名'
/

CREATE TABLE T_CHECK_RESULT
(
  ITEM_RESULT_ID     VARCHAR2(100),
  CHECK_RESULT_ID    VARCHAR2(100),
  TASK_ID            VARCHAR2(100),
  FORM_ID            VARCHAR2(100),
  TASK_FROM          VARCHAR2(100),
  FORM_NAME          VARCHAR2(100),
  TABLE_NAME         VARCHAR2(100),
  TABLE_ID           VARCHAR2(100),
  PNAME              VARCHAR2(30),
  CNAME              VARCHAR2(30),
  DNAME              VARCHAR2(30),
  STREETNAME         VARCHAR2(50),
  ITEM_ID            VARCHAR2(100),
  ITEM_TITLE         VARCHAR2(300),
  ITEM_NO            NUMBER,
  TYPE_NAME1         VARCHAR2(50),
  TYPE_NAME2         VARCHAR2(50),
  TYPE_NAME3         VARCHAR2(50),
  CONTENT_TITLE      VARCHAR2(300),
  ANSWER_RESULT      VARCHAR2(100),
  ITEM_CONTENT       CLOB,
  SCORE              NUMBER(5, 1),
  CHECK_RESULT       VARCHAR2(100),
  CHECK_DESC         VARCHAR2(100),
  PHOTO_PATH         VARCHAR2(500),
  VIEDIO_PATH        VARCHAR2(200),
  FILE_PATH          VARCHAR2(200),
  AUDIO_PATH         VARCHAR2(200),
  COMPANY_ID         VARCHAR2(100),
  COMPANY_CODE       VARCHAR2(100),
  COMPANY_NAME       VARCHAR2(100),
  CHECK_COMPANY_CODE VARCHAR2(100),
  CHECK_COMPANY_NAME VARCHAR2(100),
  PARENT_CODE        VARCHAR2(100),
  USER_ID            VARCHAR2(100),
  USER_NAME          VARCHAR2(50),
  CHECK_YEAR         VARCHAR2(10),
  CHECK_MONTH        VARCHAR2(10),
  CHECK_DATE         VARCHAR2(10),
  CHECK_WEEK         NUMBER,
  CHECK_TIME         VARCHAR2(20),
  CREATE_TIME        VARCHAR2(20),
  CREATE_USER        VARCHAR2(50),
  UPDATE_TIME        VARCHAR2(20),
  UPDATE_USER        VARCHAR2(50)
)
/

COMMENT ON TABLE T_CHECK_RESULT IS '任务执行明细表'
/

COMMENT ON COLUMN T_CHECK_RESULT.ITEM_RESULT_ID IS 'ID  主键longTime+”-"+java uuid（唯一）'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_RESULT_ID IS '检查id'
/

COMMENT ON COLUMN T_CHECK_RESULT.TASK_ID IS '任务Id'
/

COMMENT ON COLUMN T_CHECK_RESULT.FORM_ID IS '表单Id'
/

COMMENT ON COLUMN T_CHECK_RESULT.TASK_FROM IS '任务来源'
/

COMMENT ON COLUMN T_CHECK_RESULT.FORM_NAME IS '检查点名称'
/

COMMENT ON COLUMN T_CHECK_RESULT.TABLE_NAME IS '主表名根据task_from 对应不同的表'
/

COMMENT ON COLUMN T_CHECK_RESULT.TABLE_ID IS '主表id值对应的主表名id值'
/

COMMENT ON COLUMN T_CHECK_RESULT.PNAME IS '省'
/

COMMENT ON COLUMN T_CHECK_RESULT.CNAME IS '市'
/

COMMENT ON COLUMN T_CHECK_RESULT.DNAME IS '区县'
/

COMMENT ON COLUMN T_CHECK_RESULT.STREETNAME IS '街道乡镇'
/

COMMENT ON COLUMN T_CHECK_RESULT.ITEM_ID IS '检查内容库id。自定义时不存在，索引'
/

COMMENT ON COLUMN T_CHECK_RESULT.ITEM_TITLE IS '标题内容'
/

COMMENT ON COLUMN T_CHECK_RESULT.ITEM_NO IS '编号，由小到大排序'
/

COMMENT ON COLUMN T_CHECK_RESULT.TYPE_NAME1 IS '分类名称1'
/

COMMENT ON COLUMN T_CHECK_RESULT.TYPE_NAME2 IS '分类名称2'
/

COMMENT ON COLUMN T_CHECK_RESULT.TYPE_NAME3 IS '分类名称3'
/

COMMENT ON COLUMN T_CHECK_RESULT.CONTENT_TITLE IS '标题内容'
/

COMMENT ON COLUMN T_CHECK_RESULT.ANSWER_RESULT IS '回答选择。选择结果值，如1,2,3,4'
/

COMMENT ON COLUMN T_CHECK_RESULT.ITEM_CONTENT IS '选项json格式'
/

COMMENT ON COLUMN T_CHECK_RESULT.SCORE IS '得分获得分数，1位小数'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_RESULT IS '是否正常，0正常1异常（有隐患）'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_DESC IS '备注隐患备注，默认为选项内容。'
/

COMMENT ON COLUMN T_CHECK_RESULT.PHOTO_PATH IS '上传图片路径多个用逗号分隔'
/

COMMENT ON COLUMN T_CHECK_RESULT.VIEDIO_PATH IS '视频路径'
/

COMMENT ON COLUMN T_CHECK_RESULT.FILE_PATH IS '文件路径'
/

COMMENT ON COLUMN T_CHECK_RESULT.AUDIO_PATH IS '声音路径'
/

COMMENT ON COLUMN T_CHECK_RESULT.COMPANY_ID IS '单位id号'
/

COMMENT ON COLUMN T_CHECK_RESULT.COMPANY_CODE IS '检查点单位代码'
/

COMMENT ON COLUMN T_CHECK_RESULT.COMPANY_NAME IS '检查点单位名称'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_COMPANY_CODE IS '检查人单位代码'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_COMPANY_NAME IS '检查人单位名称'
/

COMMENT ON COLUMN T_CHECK_RESULT.PARENT_CODE IS '父代码'
/

COMMENT ON COLUMN T_CHECK_RESULT.USER_ID IS '用户id'
/

COMMENT ON COLUMN T_CHECK_RESULT.USER_NAME IS '用户名'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_YEAR IS '4位年'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_MONTH IS '两位月01,02'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_DATE IS '8位日期yyyymmdd'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_WEEK IS '1-7周1，7周日'
/

COMMENT ON COLUMN T_CHECK_RESULT.CHECK_TIME IS '检查时间yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN T_CHECK_RESULT.CREATE_TIME IS '创建时间yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN T_CHECK_RESULT.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN T_CHECK_RESULT.UPDATE_TIME IS '更新时间yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN T_CHECK_RESULT.UPDATE_USER IS '更新用户名'
/

CREATE TABLE T_DANGER_INFO
(
  DANGER_ID            VARCHAR2(100),
  ITEM_RESULT_ID       VARCHAR2(100),
  CHECK_RESULT_ID      VARCHAR2(100),
  TASK_ID              VARCHAR2(100),
  FORM_ID              VARCHAR2(100),
  TASK_FROM            VARCHAR2(100),
  FORM_NAME            VARCHAR2(100),
  TABLE_NAME           VARCHAR2(100),
  TABLE_ID             VARCHAR2(100),
  PNAME                VARCHAR2(30),
  CNAME                VARCHAR2(30),
  DNAME                VARCHAR2(30),
  STREETNAME           VARCHAR2(50),
  CONTENT_TITLE        VARCHAR2(300),
  ANSWER_RESULT        VARCHAR2(100),
  ITEM_CONTENT         CLOB,
  DANGER_FROM          VARCHAR2(50),
  DANGER_DESC          CHAR(10),
  PHOTO_PATH           VARCHAR2(500),
  VIEDIO_PATH          VARCHAR2(200),
  FILE_PATH            VARCHAR2(200),
  AUDIO_PATH           VARCHAR2(200),
  COMPANY_ID           VARCHAR2(100),
  COMPANY_CODE         VARCHAR2(100),
  COMPANY_NAME         VARCHAR2(100),
  CHECK_COMPANY_CODE   CHAR(10),
  CHECK_COMPANY_NAME   CHAR(10),
  PARENT_CODE          VARCHAR2(100),
  USER_ID              VARCHAR2(100),
  USER_NAME            VARCHAR2(50),
  CHECK_YEAR           VARCHAR2(10),
  CHECK_MONTH          VARCHAR2(10),
  CHECK_DATE           VARCHAR2(10),
  CHECK_WEEK           NUMBER,
  CHECK_TIME           VARCHAR2(20),
  DANGER_LEVEL         NUMBER,
  DANGER_HANDLE_TIME   VARCHAR2(20),
  DANGER_HANDLE_USERID VARCHAR2(100),
  DANGER_HANDLE_USER   VARCHAR2(20),
  DANGER_HANDLE_DESC   CLOB,
  DANGER_HANDLE_FILE   CLOB,
  PALN_FINISH_DATE     VARCHAR2(20),
  FINISHED_TIME        VARCHAR2(20),
  RECHECK_TIME         CHAR(10),
  RECHECK_USER         CHAR(10),
  RECHECK_FILE         CLOB,
  DANGER_STATUS        NUMBER,
  CREATE_TIME          VARCHAR2(20),
  CREATE_USER          VARCHAR2(50),
  UPDATE_TIME          VARCHAR2(20),
  UPDATE_USER          VARCHAR2(50),
  PROC_FLOW_INFO       CLOB
)
/

COMMENT ON TABLE T_DANGER_INFO IS '隐患表'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_ID IS 'ID主键longTime+”-"+java uuid（唯一）'
/

COMMENT ON COLUMN T_DANGER_INFO.ITEM_RESULT_ID IS '检查id号，如果有添加'
/

COMMENT ON COLUMN T_DANGER_INFO.CHECK_RESULT_ID IS '检查id'
/

COMMENT ON COLUMN T_DANGER_INFO.TASK_ID IS '任务Id'
/

COMMENT ON COLUMN T_DANGER_INFO.FORM_ID IS '表单Id'
/

COMMENT ON COLUMN T_DANGER_INFO.TASK_FROM IS '任务来源'
/

COMMENT ON COLUMN T_DANGER_INFO.FORM_NAME IS '检查点名称。。。冗余'
/

COMMENT ON COLUMN T_DANGER_INFO.TABLE_NAME IS '主表名，根据task_from 对应不同的表'
/

COMMENT ON COLUMN T_DANGER_INFO.TABLE_ID IS '主表id值。对应的主表名id值'
/

COMMENT ON COLUMN T_DANGER_INFO.PNAME IS '省'
/

COMMENT ON COLUMN T_DANGER_INFO.CNAME IS '市'
/

COMMENT ON COLUMN T_DANGER_INFO.DNAME IS '区县'
/

COMMENT ON COLUMN T_DANGER_INFO.STREETNAME IS '街道乡镇'
/

COMMENT ON COLUMN T_DANGER_INFO.CONTENT_TITLE IS '标题内容'
/

COMMENT ON COLUMN T_DANGER_INFO.ANSWER_RESULT IS '回答选择。选择结果值，如1,2,3,4'
/

COMMENT ON COLUMN T_DANGER_INFO.ITEM_CONTENT IS '选项。json格式'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_FROM IS '隐患来源。task，device，timereport（随手报）'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_DESC IS '隐患备注，默认为选项内容。'
/

COMMENT ON COLUMN T_DANGER_INFO.PHOTO_PATH IS '上传图片路径，多个用逗号分隔'
/

COMMENT ON COLUMN T_DANGER_INFO.VIEDIO_PATH IS '视频路径'
/

COMMENT ON COLUMN T_DANGER_INFO.FILE_PATH IS '文件路径'
/

COMMENT ON COLUMN T_DANGER_INFO.AUDIO_PATH IS '声音路径'
/

COMMENT ON COLUMN T_DANGER_INFO.COMPANY_ID IS '单位id号'
/

COMMENT ON COLUMN T_DANGER_INFO.COMPANY_CODE IS '单位代码，检查点单位代码'
/

COMMENT ON COLUMN T_DANGER_INFO.COMPANY_NAME IS '检查点单位名称'
/

COMMENT ON COLUMN T_DANGER_INFO.CHECK_COMPANY_CODE IS '检查人单位代码'
/

COMMENT ON COLUMN T_DANGER_INFO.CHECK_COMPANY_NAME IS '检查人单位名称'
/

COMMENT ON COLUMN T_DANGER_INFO.PARENT_CODE IS '父代码，便于统计'
/

COMMENT ON COLUMN T_DANGER_INFO.USER_ID IS '用户id'
/

COMMENT ON COLUMN T_DANGER_INFO.USER_NAME IS '用户名'
/

COMMENT ON COLUMN T_DANGER_INFO.CHECK_YEAR IS '4位，年'
/

COMMENT ON COLUMN T_DANGER_INFO.CHECK_MONTH IS '月两位月01,02'
/

COMMENT ON COLUMN T_DANGER_INFO.CHECK_DATE IS '8位日期yyyymmdd'
/

COMMENT ON COLUMN T_DANGER_INFO.CHECK_WEEK IS '1-7周1，7周日'
/

COMMENT ON COLUMN T_DANGER_INFO.CHECK_TIME IS '检查时间yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_LEVEL IS '隐患等级。0,12,34'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_HANDLE_TIME IS '整改时间'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_HANDLE_USERID IS '整改人id，指定整改时需要'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_HANDLE_USER IS '整改人'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_HANDLE_DESC IS '整改描述'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_HANDLE_FILE IS '整改附件，主要是图片'
/

COMMENT ON COLUMN T_DANGER_INFO.PALN_FINISH_DATE IS '计划完成日期yyyy-mm-dd'
/

COMMENT ON COLUMN T_DANGER_INFO.FINISHED_TIME IS '整改完成时间yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN T_DANGER_INFO.RECHECK_TIME IS '复查时间'
/

COMMENT ON COLUMN T_DANGER_INFO.RECHECK_USER IS '复查人'
/

COMMENT ON COLUMN T_DANGER_INFO.RECHECK_FILE IS '复查附件，主图片'
/

COMMENT ON COLUMN T_DANGER_INFO.DANGER_STATUS IS '状态  0待整改1整改完成待复查2已复查通过，3复查不通过'
/

COMMENT ON COLUMN T_DANGER_INFO.CREATE_TIME IS '创建时间yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN T_DANGER_INFO.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN T_DANGER_INFO.UPDATE_TIME IS '更新时间yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN T_DANGER_INFO.UPDATE_USER IS '更新用户名'
/

COMMENT ON COLUMN T_DANGER_INFO.PROC_FLOW_INFO IS '流程扭转信息保存JSON数据，包括流程描述、审批时间，审批意见，审批人，通过状态，经办人（操作用户）（0不通过1通过）'
/

CREATE TABLE T_DEVICE_INFO
(
  DEVICE_ID     VARCHAR2(100),
  DEVICE_TYPE   NUMBER,
  DEVICE_NAME   NUMBER,
  DEVICE_STATUS CHAR(10),
  COMPANY_CODE  VARCHAR2(100),
  COMPNAY_NAME  VARCHAR2(255),
  PNAME         VARCHAR2(30),
  CNAME         VARCHAR2(30),
  DNAME         VARCHAR2(30),
  STREETNAME    VARCHAR2(30),
  CREATE_TIME   VARCHAR2(20),
  CREATE_USER   VARCHAR2(50),
  UPDATE_TIME   VARCHAR2(20),
  UPDATE_USER   VARCHAR2(50)
)
/

COMMENT ON TABLE T_DEVICE_INFO IS '设备表'
/

COMMENT ON COLUMN T_DEVICE_INFO.DEVICE_ID IS '主键longTime+”-"+java uuid（唯一）'
/

COMMENT ON COLUMN T_DEVICE_INFO.DEVICE_TYPE IS '设备类型'
/

COMMENT ON COLUMN T_DEVICE_INFO.DEVICE_NAME IS '填报类型，任务表单输入类型任务设置，非任务表单通过这个来限制输入类型0不限制可随时填报1每周1次，2每月1次3只一次'
/

COMMENT ON COLUMN T_DEVICE_INFO.DEVICE_STATUS IS '设备状态'
/

COMMENT ON COLUMN T_DEVICE_INFO.COMPANY_CODE IS '所属单位代码'
/

COMMENT ON COLUMN T_DEVICE_INFO.COMPNAY_NAME IS '所属单位名称'
/

COMMENT ON COLUMN T_DEVICE_INFO.PNAME IS '省'
/

COMMENT ON COLUMN T_DEVICE_INFO.CNAME IS '市'
/

COMMENT ON COLUMN T_DEVICE_INFO.DNAME IS '区县'
/

COMMENT ON COLUMN T_DEVICE_INFO.STREETNAME IS '街道、乡镇'
/

COMMENT ON COLUMN T_DEVICE_INFO.CREATE_TIME IS '创建时间yyyy-mm-dd hh:MM:ss'
/

COMMENT ON COLUMN T_DEVICE_INFO.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN T_DEVICE_INFO.UPDATE_TIME IS '更新时间'
/

COMMENT ON COLUMN T_DEVICE_INFO.UPDATE_USER IS '更新用户名'
/

CREATE TABLE T_DEVICE_TASK
(
  TASK_FORM_ID VARCHAR2(100),
  TASK_ID      VARCHAR2(100),
  DEVICE_ID    VARCHAR2(100)
)
/

COMMENT ON TABLE T_DEVICE_TASK IS '设备检查任务表'
/

COMMENT ON COLUMN T_DEVICE_TASK.TASK_FORM_ID IS '主键longTime+”-"+java uuid（唯一）'
/

COMMENT ON COLUMN T_DEVICE_TASK.TASK_ID IS '索引'
/

COMMENT ON COLUMN T_DEVICE_TASK.DEVICE_ID IS '索引'
/

CREATE TABLE T_TASK_FORM
(
  TASK_FORM_ID VARCHAR2(100) NOT NULL
    CONSTRAINT PK_T_TASK_FORM
    PRIMARY KEY,
  TASK_ID      VARCHAR2(100),
  FORM_ID      VARCHAR2(100)
)
/

COMMENT ON TABLE T_TASK_FORM IS '任务表单表关联表'
/

COMMENT ON COLUMN T_TASK_FORM.TASK_ID IS '任务id'
/

COMMENT ON COLUMN T_TASK_FORM.FORM_ID IS '表单id'
/

CREATE TABLE T_TASK_INFO
(
  TASK_ID                    VARCHAR2(100) NOT NULL
    CONSTRAINT PK_T_TASK_INFO
    PRIMARY KEY,
  TASK_NAME                  VARCHAR2(50),
  TASK_CATEGORY              NUMBER,
  TASK_TYPE                  VARCHAR2(50),
  TASK_FROM                  VARCHAR2(50),
  PARENT_ID                  VARCHAR2(100),
  START_DATE                 VARCHAR2(20),
  END_DATE                   VARCHAR2(20),
  START_TIME                 VARCHAR2(10),
  END_TIME                   VARCHAR2(10),
  NOT_HANDLE_DAY             CLOB,
  ONLY_WORK_DAY              NUMBER,
  INFO_HANDLE_TYPE           NUMBER,
  COMPANY_CODE               VARCHAR2(100),
  COMPANY_NAME               VARCHAR2(100),
  RELEASE_PERSION            VARCHAR2(50),
  RELEASE_TIME               VARCHAR2(20),
  CHECK_TYPE                 NUMBER,
  CHECK_COMPAN_CODE          VARCHAR2(100),
  CHECK_COMPANY_NAME         VARCHAR2(100),
  FORM_TYPE                  NUMBER,
  INFO_STATUS                NUMBER,
  OBJECT_COMPANY_TYP         VARCHAR2(500),
  OBJECT_COMPANY_PARENT_CODE VARCHAR2(500),
  OBJECT_COMPANY             NUMBER DEFAULT 0,
  OBJECT_USER                NUMBER DEFAULT 0,
  TOTAL_OBJECT_NUM           NUMBER DEFAULT 0,
  CONFIRM_NUM                NUMBER DEFAULT 0,
  CHECK_COMPANY_CONFIRM_NUM  NUMBER DEFAULT 0,
  FINISHED_NUM               NUMBER DEFAULT 0,
  CHECK_COMPANY_FINISHED_NUM NUMBER DEFAULT 0,
  DANGER_NUM                 NUMBER DEFAULT 0,
  CHECK_COMPANY_DANGER_NUM   NUMBER DEFAULT 0,
  HANDLE_DANGER_NUM          NUMBER DEFAULT 0,
  APPLY_PERSON               VARCHAR2(50),
  APPLY_TIME                 VARCHAR2(20),
  CHECK_PERSON               VARCHAR2(50),
  CHECK_DESC                 VARCHAR2(200),
  CHECK_TIME                 VARCHAR2(20),
  CREATE_TIME                VARCHAR2(20),
  CREATE_USER                VARCHAR2(50),
  UPDATE_TIME                VARCHAR2(20),
  UPDATE_USER                VARCHAR2(50),
  PROC_FLOW_INFO             CLOB
)
/

COMMENT ON TABLE T_TASK_INFO IS '下发任务信息表'
/

COMMENT ON COLUMN T_TASK_INFO.TASK_ID IS 'ID'
/

COMMENT ON COLUMN T_TASK_INFO.TASK_NAME IS '任务名称(索引)'
/

COMMENT ON COLUMN T_TASK_INFO.TASK_CATEGORY IS '任务分类(0单任务，1多任务（由多个任务组成），多任务时只需设置子任务下发，主任务不单独发布2)'
/

COMMENT ON COLUMN T_TASK_INFO.TASK_TYPE IS '任务类型(该值从字典里面取值，只放DIC_NAME值)'
/

COMMENT ON COLUMN T_TASK_INFO.TASK_FROM IS '任务来源任务（TASK），设备（DEVICE），CHECKPOINT检查点等。'
/

COMMENT ON COLUMN T_TASK_INFO.PARENT_ID IS '父类ID号,(多个任务用。通过父类任务更新时更新。)'
/

COMMENT ON COLUMN T_TASK_INFO.START_DATE IS '开始时间(YYYY-MM-DD 不设置则为长期)'
/

COMMENT ON COLUMN T_TASK_INFO.END_DATE IS '结束时间YYYY-MM-DD不设置则为长期n设置后在规定时间范围内执行任务n'
/

COMMENT ON COLUMN T_TASK_INFO.START_TIME IS '开始时间 (HH:MM)'
/

COMMENT ON COLUMN T_TASK_INFO.END_TIME IS '结束时间(HH:MM)'
/

COMMENT ON COLUMN T_TASK_INFO.NOT_HANDLE_DAY IS '不包含节假日,指定节假日例外，逗号分隔的YYYY-MM-DD日期'
/

COMMENT ON COLUMN T_TASK_INFO.ONLY_WORK_DAY IS '工作日处理(0不限制1限制，n限制后周6、7不用检查n)'
/

COMMENT ON COLUMN T_TASK_INFO.INFO_HANDLE_TYPE IS '处理方式,0仅1次，1每日、2每周，3每月，4每年'
/

COMMENT ON COLUMN T_TASK_INFO.COMPANY_CODE IS '发布单位'
/

COMMENT ON COLUMN T_TASK_INFO.COMPANY_NAME IS '单位名称(便于单表查询)'
/

COMMENT ON COLUMN T_TASK_INFO.RELEASE_PERSION IS '发布人'
/

COMMENT ON COLUMN T_TASK_INFO.RELEASE_TIME IS '发布时间'
/

COMMENT ON COLUMN T_TASK_INFO.CHECK_TYPE IS '任务检查方式0目标单位自查1检查单位抽查2以上2者'
/

COMMENT ON COLUMN T_TASK_INFO.CHECK_COMPAN_CODE IS '检查单位代码,(只单个单位,建索引)'
/

COMMENT ON COLUMN T_TASK_INFO.CHECK_COMPANY_NAME IS '检查单位名称'
/

COMMENT ON COLUMN T_TASK_INFO.FORM_TYPE IS '任务内容类型(0单表单1多表单。)'
/

COMMENT ON COLUMN T_TASK_INFO.INFO_STATUS IS '状态,0待审核，1审核通过，2审核拒绝，3已发布，4已完成'
/

COMMENT ON COLUMN T_TASK_INFO.OBJECT_COMPANY_TYP IS '对象单位类型(对应单位类型中COMPANY_TYPE,可多个（依赖单位信息分类正确）。按单位类型来选择，多个逗号分隔)'
/

COMMENT ON COLUMN T_TASK_INFO.OBJECT_COMPANY_PARENT_CODE IS '对象父代码,单位类型中PARENT_CODE,按上级单位选择，多个逗号分隔'
/

COMMENT ON COLUMN T_TASK_INFO.OBJECT_COMPANY IS '指定单位,0所有下级，1本单位，2本单位及下级，3指定单位，9为所有 (注册类型为0,1的只能是0,1,2、3)'
/

COMMENT ON COLUMN T_TASK_INFO.OBJECT_USER IS '指定用户 0不指定1，指定人'
/

COMMENT ON COLUMN T_TASK_INFO.TOTAL_OBJECT_NUM IS '总指定对象数'
/

COMMENT ON COLUMN T_TASK_INFO.CONFIRM_NUM IS '认领数自查单位认领数'
/

COMMENT ON COLUMN T_TASK_INFO.CHECK_COMPANY_CONFIRM_NUM IS '检查单位认领数'
/

COMMENT ON COLUMN T_TASK_INFO.FINISHED_NUM IS '完成数,自查单位完成数'
/

COMMENT ON COLUMN T_TASK_INFO.CHECK_COMPANY_FINISHED_NUM IS '检查单位完成数'
/

COMMENT ON COLUMN T_TASK_INFO.DANGER_NUM IS '隐患数,自查隐患数'
/

COMMENT ON COLUMN T_TASK_INFO.CHECK_COMPANY_DANGER_NUM IS '检查单位检查隐患数'
/

COMMENT ON COLUMN T_TASK_INFO.HANDLE_DANGER_NUM IS '整改隐患数'
/

COMMENT ON COLUMN T_TASK_INFO.APPLY_PERSON IS '申请人'
/

COMMENT ON COLUMN T_TASK_INFO.APPLY_TIME IS '申请时间'
/

COMMENT ON COLUMN T_TASK_INFO.CHECK_PERSON IS '审批人'
/

COMMENT ON COLUMN T_TASK_INFO.CHECK_DESC IS '审批备注'
/

COMMENT ON COLUMN T_TASK_INFO.CHECK_TIME IS '审批时间'
/

COMMENT ON COLUMN T_TASK_INFO.CREATE_TIME IS '创建时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN T_TASK_INFO.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN T_TASK_INFO.UPDATE_TIME IS '更新时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN T_TASK_INFO.UPDATE_USER IS '更新用户名'
/

COMMENT ON COLUMN T_TASK_INFO.PROC_FLOW_INFO IS '流程扭转信息'
/

CREATE TABLE T_TASK_OBJECT_INFO
(
  TASK_OBJCT_ID      VARCHAR2(100) NOT NULL
    CONSTRAINT PK_T_TASK_OBJECT_INFO
    PRIMARY KEY,
  TASK_ID            VARCHAR2(100),
  COMPANY_CODE       VARCHAR2(50),
  COMPANY_NAME       VARCHAR2(100),
  CHECK_COMPANY_CODE VARCHAR2(50),
  CHECK_COMPANY_NAME VARCHAR2(100),
  USER_ID            VARCHAR2(100),
  USER_NAME          VARCHAR2(50),
  TASK_OBJCT_TYPE    NUMBER DEFAULT 0,
  CONFIRM_TIME       VARCHAR2(20),
  CONFIRM_USER_ID    VARCHAR2(100),
  CONFIRM_USER_NAME  VARCHAR2(50),
  TASK_START_TIME    VARCHAR2(20),
  TASK_END_TIME      VARCHAR2(20),
  HANDLE_TIME        VARCHAR2(20),
  HANDLE_USER_ID     VARCHAR2(100),
  HANDLE_USER_NAME   VARCHAR2(50),
  STATUS             NUMBER,
  CHECK_REMARK       CLOB,
  TOTAL_CHECK_NUM    NUMBER,
  FINISHED_CHECK_NUM NUMBER,
  DANGER_NUM         NUMBER,
  HANDLE_DANGER_NUM  NUMBER,
  CREATE_TIME        VARCHAR2(20),
  CREATE_USER        VARCHAR2(50),
  UPDATE_TIME        VARCHAR2(20),
  UPDATE_USER        VARCHAR2(50),
  TASK_TYPE          VARCHAR2(50)
)
/

COMMENT ON TABLE T_TASK_OBJECT_INFO IS '任务对象表'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.TASK_OBJCT_ID IS 'ID'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.TASK_ID IS '任务ID,索引'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.COMPANY_CODE IS '单位代码,指定单位时存在n索引
'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.COMPANY_NAME IS '单位名称,冗余，便于单表查询'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.CHECK_COMPANY_CODE IS '第三方检查单位代码'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.CHECK_COMPANY_NAME IS '第三方检查单位名称'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.USER_ID IS '用户ID,指定人时存在'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.USER_NAME IS '用户名   ,冗余，便于单表查询'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.TASK_OBJCT_TYPE IS '对象分类   0 单位1指定人'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.CONFIRM_TIME IS '认领时间  YYYY-MM-DD HH:MM:SS'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.CONFIRM_USER_ID IS '认领用户ID'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.CONFIRM_USER_NAME IS '认领用户名'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.TASK_START_TIME IS '开始处理时间nYYYY-MM-DD HH:MM:SS
第一次处理时间n'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.TASK_END_TIME IS '完成时间  YYYY-MM-DD HH:MM:SS'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.HANDLE_TIME IS '处理时间  ,最近一次处理时间YYYY-MM-DD HH:MM:SS'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.HANDLE_USER_ID IS '处理人ID'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.HANDLE_USER_NAME IS '处理人名'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.STATUS IS '任务状态(0待认领1已认领处理中2退回，3已完成4已过期)'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.CHECK_REMARK IS '备注'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.TOTAL_CHECK_NUM IS '总共检查项数(对于定制表单无)'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.FINISHED_CHECK_NUM IS '完成检查项数(对于定制表单无)'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.DANGER_NUM IS '隐患数'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.HANDLE_DANGER_NUM IS '整改隐患数'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.CREATE_TIME IS '创建时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.CREATE_USER IS '创建用户名'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.UPDATE_TIME IS '更新时间(YYYY-MM-DD HH:MM:SS)'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.UPDATE_USER IS '更新用户名'
/

COMMENT ON COLUMN T_TASK_OBJECT_INFO.TASK_TYPE IS '任务类型(该值从字典里面取值 只放DIC_NAME)'
/

